version: '3.8'

services:
  zerodha-backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: zerodha-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CHROME_BIN=/usr/bin/chromium
      - DISPLAY=:99
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/market_status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M 