services:
  - type: web
    name: zerodha-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: KITE_API_KEY
        sync: false
      - key: KITE_API_SECRET
        sync: false
      - key: KITE_USERNAME
        sync: false
      - key: KITE_PASSWORD
        sync: false
      - key: TOTP_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_BIN
        value: /usr/local/bin/chromedriver
      - key: DISPLAY
        value: :99 