services:
  - type: web
    name: zerodha-backend
    env: docker
    dockerfilePath: Backend/Dockerfile
    envVars:
      - key: KITE_API_KEY
        sync: false
      - key: KITE_API_SECRET
        sync: false
      - key: KITE_USERNAME
        sync: false
      - key: KITE_PASSWORD
        sync: false
      - key: TOTP_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: FMP_API_KEY
        sync: false
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: CHROMEDRIVER_BIN
        value: /usr/bin/chromedriver
      - key: DISPLAY
        value: :99 